drop table users_roles;
drop table users_checkpoints;
drop table cell_checkpoints;
drop table checkpoints;
drop table cell;
drop table stage;
drop table runway;
drop table users;
alter table flightplan drop column department_id;
alter table department drop column currentplan_id;
drop table department;
drop table flightplan;
drop table roles;
drop sequence hibernate_sequence;